# arm0:
#   kinematics_solver: co605_dual_arm_gripper_arm0_kinematics/IKFastKinematicsPlugin
#   kinematics_solver_attempts: 3
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.05
# arm1:
#   kinematics_solver: co605_dual_arm_gripper_arm1_kinematics/IKFastKinematicsPlugin
#   kinematics_solver_attempts: 3
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.05
# kdl_kinematics_plugin/KDLKinematicsPlugin trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
arm0:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 4
arm1:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 4
