controller_list:
  - name: "UR51"
    action_ns: joint_trajectory_action
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: "UR52"
    action_ns: joint_trajectory_action
    default: True
    type: FollowJointTrajectory
    joints:
      - R_joint_1
      - R_joint_2
      - R_joint_3
      - R_joint_4
      - R_joint_5
      - R_joint_6
